export const DATA = {
    linux: [
        "ls -la : Tüm dosyaları gizlilerle birlikte listeler",
        "cd /var/www : Web klasörüne geçiş yapar",
        "mkdir proje_yedek : Yedek klasörü oluşturur",
        "touch config.json : Boş bir konfigürasyon dosyası açar",
        "rm -rf node_modules : Klasörü kalıcı olarak siler",
        "cp -r kaynak hedef : Klasörü kopyalar",
        "mv eski_ad yeni_ad : Dosya adını değiştirir",
        "cat /etc/passwd : Kullanıcı listesini ekrana basar",
        "tail -f error.log : Hata loglarını canlı izler",
        "grep 'error' app.log : Log dosyasında hata arar",
        "chmod 755 script.sh : Dosyaya çalıştırma izni verir",
        "chown www-data:www-data site : Dosya sahibini değiştirir",
        "ps aux | grep nginx : Nginx işlemlerini bulur",
        "top : Sistem kaynaklarını canlı gösterir",
        "htop : Renkli işlem yöneticisi",
        "kill -9 1234 : İşlemi zorla sonlandırır",
        "systemctl restart apache2 : Servisi yeniden başlatır",
        "systemctl status mysql : Veritabanı durumunu gösterir",
        "df -h : Disk doluluk oranını gösterir",
        "free -m : RAM kullanımını gösterir",
        "du -sh . : Bulunduğun klasörün boyutunu ölçer",
        "find / -name *.conf : Tüm sistemde conf dosyası arar",
        "tar -czvf backup.tar.gz . : Klasörü sıkıştırır",
        "unzip dosya.zip : Zip arşivini açar",
        "ssh root@192.168.1.50 : Uzak sunucuya bağlanır",
        "scp file.txt user@host:/tmp : Sunucuya dosya atar",
        "wget https://file.com : Dosya indirir",
        "curl -I google.com : Site başlıklarını kontrol eder",
        "ping 8.8.8.8 : İnternet bağlantısını test eder",
        "netstat -tulnp : Açık portları dinler",
        "ufw allow 80/tcp : 80 portuna izin verir",
        "history | grep ssh : SSH geçmişini arar",
        "whoami : Mevcut kullanıcıyı gösterir",
        "sudo su - : Root kullanıcısına geçer",
        "apt update && apt upgrade : Sistemi günceller",
        "echo $PATH : Ortam değişkenlerini gösterir",
        "ln -s hedef link : Sembolik link oluşturur",
        "uname -a : Çekirdek sürümünü gösterir",
        "lscpu : İşlemci özelliklerini gösterir",
        "lsblk : Disk bölümlerini listeler"
    ],
    cyber: [
        "nmap -sV 192.168.1.1 : Servis sürümlerini tarar",
        "sqlmap -u target.com --dbs : Veritabanlarını çeker",
        "burpsuite : Web proxy ve analiz aracı",
        "metasploit console : Sızma testi konsolunu açar",
        "hydra -l admin -P list.txt ssh://ip : Parola dener",
        "aircrack-ng wlan0 : Kablosuz ağ şifresi kırar",
        "wireshark : Ağ paketlerini yakalar ve analiz eder",
        "gobuster dir -u url -w wordlist : Gizli dizin arar",
        "nikto -h http://site.com : Web zafiyet taraması",
        "hashcat -m 0 hash.txt : MD5 şifresi kırar",
        "netcat -lvnp 4444 : Ters bağlantı dinler",
        "whois domain.com : Domain sahibini sorgular",
        "sublist3r -d domain.com : Alt alan adlarını bulur",
        "wpscan --url site.com : Wordpress açığı tarar",
        "bettercap : Ağ saldırıları (MITM) yapar"
    ],
    network: [
        "ip addr show : IP adreslerini listeler",
        "traceroute google.com : Paketin izlediği yolu gösterir",
        "nslookup google.com : DNS kaydını çözer",
        "dig domain.com ANY : Tüm DNS kayıtlarını getirir",
        "arp -a : Ağdaki cihazların MAC adreslerini döker",
        "tcpdump -i eth0 : Ağ trafiğini terminale basar",
        "route -n : Yönlendirme tablosunu gösterir",
        "ssh-keygen -t rsa : SSH anahtarı oluşturur",
        "telnet localhost 25 : Mail portunu test eder",
        "macchanger -r eth0 : MAC adresini rastgele değiştirir",
        "ethtool eth0 : Ağ kartı özelliklerini gösterir",
        "nmcli dev wifi : Kablosuz ağları listeler"
    ],
    web: [
        "display: flex : Esnek kutu modelini açar",
        "justify-content: center : Yatayda ortalar",
        "align-items: center : Dikeyde ortalar",
        "grid-template-columns : Izgara sütunlarını ayarlar",
        "z-index: 999 : Katman önceliğini belirler",
        "box-shadow: 0 0 10px : Kutuya gölge verir",
        "border-radius: 50% : Tam yuvarlak yapar",
        "@media screen and (max-width) : Mobil uyumluluk",
        "transform: translate(-50%) : Konumu kaydırır",
        "cursor: pointer : Fare imlecini el yapar",
        "overflow: hidden : Taşan içeriği gizler",
        "background: linear-gradient : Renk geçişi yapar"
    ],
    js: [
        "console.log('Debug') : Konsola veri yazar",
        "document.querySelector('#id') : Element seçer",
        "element.addEventListener('click', fn) : Tıklamayı dinler",
        "JSON.stringify(data) : Veriyi metne çevirir",
        "JSON.parse(json) : Metni objeye çevirir",
        "localStorage.setItem('key', 'val') : Veri kaydeder",
        "fetch('https://api.com') : Veri çeker (Ajax)",
        "array.map(item => item.id) : Diziyi dönüştürür",
        "array.filter(item => item.active) : Filtreleme yapar",
        "array.reduce((acc, curr) => acc + curr) : Toplama yapar",
        "async function getData() : Asenkron fonksiyon",
        "await promise : İşlemin bitmesini bekler",
        "export default class Main : Modül dışa aktarır",
        "const { id, name } = user : Destructuring işlemi",
        "items = [...oldItems, newItem] : Spread operatörü"
    ],
    python: [
        "import pandas as pd : Veri analizi kütüphanesi",
        "def calculate_sum(a, b): : Fonksiyon tanımı",
        "list_comp = [x*2 for x in range(10)] : Liste üreteci",
        "dictionary = {'key': 'value'} : Sözlük yapısı",
        "if __name__ == '__main__': : Ana modül kontrolü",
        "try: code except Exception as e: : Hata yönetimi",
        "with open('file.txt', 'r') as f: : Dosya okuma",
        "class NeuralNetwork(nn.Module): : Sınıf tanımı",
        "pip install -r requirements.txt : Paketleri yükler",
        "virtualenv venv : Sanal ortam oluşturur",
        "lambda x: x + 1 : İsimsiz fonksiyon",
        "matplotlib.pyplot.plot(data) : Grafik çizer",
        "df.groupby('col').mean() : Veriyi gruplar",
        "requests.get('url').json() : HTTP isteği atar"
    ],
    csharp: [
        "Console.WriteLine($\"Val: {x}\"); : Ekrana yazar",
        "public static void Main(string[] args) : Giriş noktası",
        "var list = new List<string>(); : Liste oluşturur",
        "int.TryParse(input, out int res) : Güvenli çeviri",
        "using System.Linq; : Sorgu kütüphanesi",
        "foreach (var item in items) : Döngü yapısı",
        "public async Task<IActionResult> Get() : Asenkron API",
        "await _context.SaveChangesAsync(); : Veritabanına yazar",
        "services.AddScoped<IService>(); : Bağımlılık ekler",
        "[HttpGet(\"{id}\")] : Route tanımlaması",
        "throw new ArgumentNullException(); : Hata fırlatır",
        "public class User : IdentityUser : Kalıtım alır"
    ],
    sql: [
        "SELECT * FROM users WHERE active = 1 : Veri çeker",
        "INSERT INTO logs (msg) VALUES ('Err') : Veri ekler",
        "UPDATE products SET price = 99 : Güncelleme yapar",
        "DELETE FROM cart WHERE id = 5 : Veri siler",
        "SELECT COUNT(*) FROM orders : Toplam sayıyı verir",
        "INNER JOIN categories ON c.id = p.cat_id : Tablo birleştirir",
        "LEFT JOIN users ON u.id = o.user_id : Soldan birleştirir",
        "GROUP BY city HAVING count > 5 : Gruplama yapar",
        "ORDER BY created_at DESC : Tarihe göre sıralar",
        "CREATE TABLE students (id INT) : Tablo oluşturur",
        "ALTER TABLE users ADD age INT : Kolon ekler",
        "TRUNCATE TABLE logs : Tabloyu tamamen boşaltır",
        "BEGIN TRANSACTION; COMMIT; : İşlem bütünlüğü"
    ],
    devops: [
        "docker run -d -p 80:80 nginx : Konteyner başlatır",
        "docker build -t app:v1 . : İmaj oluşturur",
        "docker-compose up -d : Servisleri kaldırır",
        "kubectl get pods -n kube-system : Podları listeler",
        "kubectl logs deployment/app : Logları okur",
        "kubectl apply -f deployment.yaml : Ayarı uygular",
        "git commit -m 'feat: new login' : Versiyon kaydeder",
        "git push origin main : Sunucuya yollar",
        "jenkins build job : Derlemeyi başlatır",
        "terraform init && terraform apply : Altyapıyı kurar",
        "ansible-playbook server.yml : Konfigürasyonu yayar",
        "aws s3 ls s3://bucket : Bulut dosyalarını görür"
    ],
    english: [
        "Deployment : Canlı ortama alma işlemi",
        "Authentication : Kimlik doğrulama",
        "Authorization : Yetkilendirme",
        "Latency : Gecikme süresi",
        "Throughput : İşlem hacmi",
        "Bandwidth : Bant genişliği",
        "Scalability : Ölçeklenebilirlik",
        "Maintenance : Bakım modu",
        "Deprecated : Kullanımdan kaldırılmış",
        "Inheritance : Miras alma / Kalıtım",
        "Encapsulation : Kapsülleme / Gizleme",
        "Concurrency : Eş zamanlılık",
        "Vulnerability : Güvenlik zafiyeti",
        "Encryption : Şifreleme işlemi",
        "Algorithm : Çözüm yolu algoritma"
    ]
};